; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Volume slides are used, you must set FAMISTUDIO_USE_VOLUME_SLIDES = 1.
; Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.
; Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_pppppp=music_data_pppppp
.endif

music_data_pppppp:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Pushing Onwards
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_pppppp
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env3,@env5,@env7,@env0 ; 00 : Weird 20
	.word @env3,@env5,@env11,@env0 ; 01 : Lead
	.word @env3,@env12,@env7,@env0 ; 02 : Double Square
	.word @env3,@env5,@env9,@env0 ; 03 : Bass
	.word @env3,@env5,@env7,@env0 ; 04 : Drums

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c0,$be,$bd,$bd,$be,$bf,$c1,$c2,$c3,$c3,$c2,$00,$01
@env2:
	.byte $00,$c0,$bf,$be,$be,$bf,$c1,$c2,$c2,$c1,$00,$01
@env3:
	.byte $00,$cf,$7f,$00,$02
@env4:
	.byte $00,$c0,$bd,$bc,$be,$c2,$c4,$c3,$00,$01
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $00,$c0,$bd,$be,$c2,$c3,$00,$01
@env7:
	.byte $7f,$00,$00
@env8:
	.byte $00,$c0,$bc,$ba,$bc,$c0,$c4,$c6,$c4,$00,$01
@env9:
	.byte $c2,$7f,$00,$00
@env10:
	.byte $00,$c0,$be,$bd,$be,$c0,$c2,$c3,$c2,$00,$01
@env11:
	.byte $c1,$7f,$00,$00
@env12:
	.byte $c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$c0,$cc,$00,$3f
@env13:
	.byte $00,$c0,$be,$bc,$bc,$bd,$bf,$c1,$c3,$c4,$c4,$c2,$00,$01

@samples:
	.byte $28+.lobyte(FAMISTUDIO_DPCM_PTR),$4c,$0f,$40 ; 00 mixed (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$4c,$0f,$40 ; 01 v kick (Pitch:15)
	.byte $1a+.lobyte(FAMISTUDIO_DPCM_PTR),$38,$0f,$40 ; 02 v snare (Pitch:15)
	.byte $13+.lobyte(FAMISTUDIO_DPCM_PTR),$1c,$0f,$40 ; 03 vvv_hihat (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $c7, $48, $ff, $c7, $48, $7f
@song0ref12:
	.byte $82
@song0ref13:
	.byte $15, $8b, $00, $89, $10, $95, $15, $97, $17, $af, $18, $c7, $48, $18, $81, $1a, $c5, $18, $89, $17, $89, $17, $18, $ad
	.byte $17, $97, $13, $95, $48, $17, $8b, $00, $89, $13, $ab, $16, $81, $17, $af, $18, $c7, $48, $13, $85, $15, $c1, $18, $89
	.byte $17, $89, $14, $85, $15, $a7, $14, $97, $10, $95, $48
	.byte $41, $27
	.word @song0ref13
@song0ref75:
	.byte $48, $1a, $af, $50, $fc, $26, $28, $af, $1c
@song0ref84:
	.byte $e1, $48
@song0ref86:
	.byte $21, $8b, $00, $89, $21, $89, $00, $89, $1f, $8b, $00, $89, $20, $83, $49, .lobyte(@env8), .hibyte(@env8), $21, $a9
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $82, $24, $89, $00, $89, $23, $97, $1f, $95, $48, $50, $f5, $2b, $2d, $8b
	.byte $21, $c7, $50, $06, $2d, $2c, $89, $1f, $e1, $48, $80
@song0ref135:
	.byte $21, $8b, $00, $89, $21, $89, $00, $89, $21, $8b, $00, $89, $20, $83, $49, .lobyte(@env8), .hibyte(@env8), $21, $a9
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $24, $89, $00, $89, $21, $97, $1d, $95, $48, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $1f, $af, $49, .lobyte(@env0), .hibyte(@env0), $4a, $24, $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $23, $f9
	.byte $48, $82
	.byte $41, $3e
	.word @song0ref86
	.byte $48
	.byte $41, $37
	.word @song0ref12
	.byte $48
	.byte $41, $37
	.word @song0ref13
	.byte $48
	.byte $41, $27
	.word @song0ref13
	.byte $41, $44
	.word @song0ref75
	.byte $48, $82
	.byte $41, $3e
	.word @song0ref86
	.byte $48, $82
@song0ref213:
	.byte $21, $8b, $00, $89, $21, $89, $00, $89, $1f, $8b, $00, $89, $20, $83, $49, .lobyte(@env8), .hibyte(@env8), $21, $a9
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $82, $24, $89, $00, $89, $23, $97, $1f, $95, $48, $32, $8b, $00, $89, $34
	.byte $95, $00, $97, $30, $89, $00, $89, $32, $8b, $00, $89, $32, $89, $00, $89, $2d, $97, $2b, $95, $48, $2d, $8b, $2b, $89
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $2d, $af, $51, $f8, $30, $49, .lobyte(@env0), .hibyte(@env0), $4a, $50, $02
	.byte $39, $37, $af, $7f, $1d, $95, $00, $97, $1d, $95, $48, $50, $fc, $2f, $30, $8b, $24, $c7, $50, $05, $30, $2f, $89, $26
	.byte $41, $3f
	.word @song0ref84
	.byte $48
	.byte $41, $1e
	.word @song0ref135
	.byte $48, $24, $97, $21, $a9, $22, $83, $23, $af, $1f, $95, $1d, $97, $1c, $95, $48, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $1f, $af, $49, .lobyte(@env0), .hibyte(@env0), $4a, $24, $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $23, $f9
	.byte $48
	.byte $41, $1b
	.word @song0ref12
	.byte $48
	.byte $41, $1b
	.word @song0ref13
	.byte $48
	.byte $41, $1b
	.word @song0ref13
	.byte $48
	.byte $41, $1b
	.word @song0ref13
	.byte $48
	.byte $41, $37
	.word @song0ref13
	.byte $48
	.byte $41, $37
	.word @song0ref13
	.byte $48
	.byte $41, $37
	.word @song0ref13
	.byte $48
	.byte $41, $27
	.word @song0ref13
	.byte $48, $50, $ea, $1f, $21, $8b, $15, $c7, $50, $0b, $21, $20, $89, $14, $e1, $48
	.byte $41, $45
	.word @song0ref213
	.byte $e1, $48
	.byte $41, $45
	.word @song0ref213
@song0ref411:
	.byte $e1, $48, $84
@song0ref414:
	.byte $27, $85, $28, $a1, $50, $32, $34, $2e, $83, $21, $8b, $00, $89, $24, $95, $49, .lobyte(@env10), .hibyte(@env10), $8d
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $84, $50, $0f, $30, $2d, $89, $21, $89, $00, $89, $24, $8b, $00, $89, $21
	.byte $8f, $28, $83, $48, $29, $af, $28, $8b, $00, $89, $24, $e1, $49, .lobyte(@env6), .hibyte(@env6), $97, $48, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $84, $23, $af, $24, $97, $00, $89, $26, $89, $00, $97, $1f, $89, $00, $89, $23, $8b, $00, $89
	.byte $26, $89, $00, $83, $28, $83, $48, $29, $a9, $50, $f3, $35, $37, $83, $2b, $8b, $00, $95, $26, $83, $00, $83, $28, $8b
	.byte $00, $89, $26, $89, $00, $89, $24, $8b, $00, $89, $23, $89, $00, $89, $48
	.byte $41, $3c
	.word @song0ref414
	.byte $48, $26, $af, $28, $8b, $00, $95, $28, $83, $26, $83, $25, $e1, $48, $00, $ff, $c5, $48, $ff, $c7, $48, $ff, $c7, $48
	.byte $ff, $c7, $48
	.byte $41, $37
	.word @song0ref12
	.byte $48
	.byte $41, $37
	.word @song0ref13
	.byte $48
	.byte $41, $1b
	.word @song0ref13
	.byte $48
	.byte $41, $1b
	.word @song0ref13
	.byte $48
	.byte $41, $37
	.word @song0ref13
	.byte $48
	.byte $41, $27
	.word @song0ref13
	.byte $48, $50, $fc, $2f, $30, $8b, $24, $c7, $50, $05, $30, $2f, $89, $26
	.byte $41, $59
	.word @song0ref411
	.byte $48
	.byte $41, $3c
	.word @song0ref414
	.byte $48, $26, $af, $28, $8b, $00, $95, $28, $83, $26, $83, $25, $e1, $48, $25, $8b, $23, $89, $25, $89, $23, $89, $25, $8b
	.byte $23, $89, $25, $89, $23, $89, $25, $8b, $23, $89, $25, $89, $23, $89, $25, $85, $23, $83, $25, $83, $23, $83, $25, $83
	.byte $23, $83, $25, $83, $23, $83, $48, $25, $8b, $51, $f5, $90, $91, $51, $0b, $f0, $91, $99, $77, $8b, $72, $a5, $00, $c7
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $86
@song0ref682:
	.byte $09, $8b, $00, $89, $15, $89, $10, $89, $09, $8b, $00, $89, $15, $89, $10, $89, $09, $8b, $00, $89, $15, $89, $10, $89
	.byte $09, $8b, $00, $89, $15, $89, $10, $89
	.byte $41, $20
	.word @song0ref682
	.byte $41, $20
	.word @song0ref682
@song0ref720:
	.byte $05, $8b, $00, $89, $11, $89, $0c, $89, $05, $8b, $00, $89, $11, $89, $0c, $89
@song0ref736:
	.byte $05, $8b, $00, $89, $11, $89, $0c, $89, $05, $8b, $00, $89, $11, $89, $0c, $89, $07, $8b, $00, $89, $13, $89, $0e, $89
	.byte $07, $8b, $00, $89, $13, $89, $0e
@song0ref767:
	.byte $89, $07, $8b, $00, $89, $13, $89, $0e, $89, $07, $8b, $00, $89, $13, $89, $0e, $89, $05, $8b, $00, $89, $11, $89, $0c
	.byte $89, $05, $8b, $00, $89, $11, $89, $0c, $89, $04, $8b, $00, $89, $10, $89, $0b, $89, $04, $8b, $00, $89, $10, $89, $0b
	.byte $89
	.byte $41, $20
	.word @song0ref682
	.byte $41, $60
	.word @song0ref720
@song0ref822:
	.byte $02, $8b, $00, $89, $0e, $89, $09, $89, $02, $8b, $00, $89, $0e, $89, $09, $89, $02, $8b, $00, $89, $0e, $89, $09, $89
	.byte $02, $8b, $00, $89, $0e, $89, $09, $89, $09, $8b, $00, $89, $15, $89, $10, $89, $09, $8b, $00, $89, $15, $89, $10
	.byte $41, $21
	.word @song0ref767
@song0ref872:
	.byte $05, $8b, $00, $89, $11, $89, $0c, $89, $05, $8b, $00, $89, $11, $89, $0c, $89
@song0ref888:
	.byte $0c, $8b, $00, $89, $18, $89, $13, $89, $0c, $8b, $00, $89, $18, $89, $13, $89, $04, $8b, $00, $89, $10, $89, $0b, $89
	.byte $04, $8b, $00, $89, $10, $89, $0b, $89
	.byte $41, $2f
	.word @song0ref822
	.byte $41, $21
	.word @song0ref767
	.byte $41, $30
	.word @song0ref872
	.byte $41, $20
	.word @song0ref682
	.byte $41, $60
	.word @song0ref720
	.byte $41, $20
	.word @song0ref682
	.byte $41, $60
	.word @song0ref720
	.byte $41, $20
	.word @song0ref682
	.byte $41, $60
	.word @song0ref720
	.byte $41, $2f
	.word @song0ref822
	.byte $41, $21
	.word @song0ref767
	.byte $41, $30
	.word @song0ref872
	.byte $41, $2f
	.word @song0ref822
	.byte $89, $07, $8b, $00, $89, $13, $89, $0e, $89, $07, $8b, $00, $89, $13, $89, $0e, $89
	.byte $41, $20
	.word @song0ref822
	.byte $41, $20
	.word @song0ref888
	.byte $41, $20
	.word @song0ref720
@song0ref985:
	.byte $09, $8b, $00, $89, $15, $89, $10, $89, $09, $8b, $00, $89, $15, $89, $10, $89, $07, $8b, $00, $89, $13, $89, $0e, $89
	.byte $07, $8b, $00, $89, $13, $89, $0e, $89
	.byte $41, $2f
	.word @song0ref822
	.byte $89, $07, $8b, $00, $89, $13, $89, $0e, $89, $07, $8b, $00, $89, $13, $89, $0e, $89
	.byte $41, $2f
	.word @song0ref822
	.byte $41, $21
	.word @song0ref767
	.byte $41, $30
	.word @song0ref872
	.byte $41, $20
	.word @song0ref720
	.byte $41, $20
	.word @song0ref888
	.byte $41, $20
	.word @song0ref736
	.byte $41, $20
	.word @song0ref888
	.byte $41, $20
	.word @song0ref682
	.byte $41, $20
	.word @song0ref720
	.byte $41, $20
	.word @song0ref682
	.byte $41, $20
	.word @song0ref720
	.byte $41, $20
	.word @song0ref682
	.byte $41, $20
	.word @song0ref720
	.byte $41, $20
	.word @song0ref682
	.byte $41, $20
	.word @song0ref720
	.byte $41, $20
	.word @song0ref682
	.byte $41, $60
	.word @song0ref720
	.byte $41, $20
	.word @song0ref682
	.byte $41, $60
	.word @song0ref720
	.byte $41, $20
	.word @song0ref682
	.byte $41, $60
	.word @song0ref720
	.byte $41, $20
	.word @song0ref682
	.byte $41, $60
	.word @song0ref720
	.byte $41, $20
	.word @song0ref720
	.byte $41, $20
	.word @song0ref985
	.byte $41, $2f
	.word @song0ref822
	.byte $41, $21
	.word @song0ref767
	.byte $05, $8b, $00, $89, $11, $89, $0c, $89, $05, $8b, $00, $89, $11, $89, $0c, $89
	.byte $41, $20
	.word @song0ref985
	.byte $41, $20
	.word @song0ref822
	.byte $41, $1b
	.word @song0ref736
	.byte $a1
	.byte $41, $20
	.word @song0ref682
	.byte $41, $40
	.word @song0ref720
@song0ref1150:
	.byte $0c, $8b, $00, $89, $0c, $89, $00, $89, $40, $0c, $8b, $00, $89, $0c, $89, $00, $89, $04, $8b, $00, $89, $10, $89, $0b
	.byte $89, $04, $8b, $00, $89, $10, $89, $0b, $89
	.byte $41, $20
	.word @song0ref682
	.byte $41, $40
	.word @song0ref720
	.byte $09, $8b, $00, $89, $09, $89, $00, $a3, $09, $89, $00, $89, $09, $8b, $00, $89, $15, $89, $10, $89, $09, $8b, $00, $a1
	.byte $41, $20
	.word @song0ref682
	.byte $41, $20
	.word @song0ref720
	.byte $41, $20
	.word @song0ref682
	.byte $41, $20
	.word @song0ref720
	.byte $41, $20
	.word @song0ref682
	.byte $41, $60
	.word @song0ref720
	.byte $41, $20
	.word @song0ref682
	.byte $41, $60
	.word @song0ref720
	.byte $41, $20
	.word @song0ref682
	.byte $41, $20
	.word @song0ref720
	.byte $41, $20
	.word @song0ref682
	.byte $41, $20
	.word @song0ref720
	.byte $41, $20
	.word @song0ref682
	.byte $41, $60
	.word @song0ref720
	.byte $41, $20
	.word @song0ref682
	.byte $41, $50
	.word @song0ref720
	.byte $07, $8b, $00, $89, $13, $89, $0e, $89, $07, $8b, $00, $a1
	.byte $41, $20
	.word @song0ref682
	.byte $41, $40
	.word @song0ref720
	.byte $41, $20
	.word @song0ref1150
	.byte $41, $20
	.word @song0ref682
	.byte $41, $40
	.word @song0ref720
	.byte $09, $8b, $00, $89, $09, $89, $00, $a3, $09, $89, $00, $89, $09, $8b, $00, $89, $15, $89, $10, $89, $09, $8b, $00, $a1
	.byte $41, $20
	.word @song0ref682
	.byte $41, $20
	.word @song0ref682
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
@song0ref1322:
	.byte $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7
	.byte $ff, $c7
	.byte $41, $1a
	.word @song0ref1322
	.byte $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7
	.byte $80, $34, $8b, $30, $89, $35, $89, $32
@song0ref1383:
	.byte $89, $34, $8b, $30, $89, $35, $89, $32, $89, $34, $8b, $30, $89, $35, $89, $32, $89, $34, $8b, $30, $89
@song0ref1404:
	.byte $35, $89, $32, $89, $34, $8b, $30, $89, $34, $89, $30, $89, $34, $8b, $30, $89, $34, $89, $30, $89, $34, $8b, $32, $89
	.byte $30, $89, $2d, $89, $35, $8b, $34, $89, $30, $89, $2d
	.byte $41, $1d
	.word @song0ref1383
	.byte $41, $23
	.word @song0ref1404
	.byte $89, $00, $ff, $c5, $ff, $c7, $ff, $c7, $ff, $c7, $99, $39, $89, $3b, $89, $3c, $8b, $39, $89, $3e, $af, $40, $4c, $bb
	.byte $40, $4c, $83, $40, $4d, $83, $40, $4f, $af, $40, $4c, $97, $3e, $f9, $00, $ff, $b9, $3e, $83, $40, $4c, $83, $40, $4f
	.byte $af, $40, $4c, $97, $3e, $f9, $00, $ff, $c5, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $7f
@song0ref1513:
	.byte $28, $8b, $51, $e8, $60, $8b, $51, $18, $f0, $8b, $8b, $28, $8b, $00, $89, $28, $83, $00, $83, $28, $91, $00, $83, $28
	.byte $83, $00, $83, $28, $95, $28, $8b, $00, $89, $28, $83, $00, $83, $26, $83, $00, $83, $29, $8b, $51, $e8, $60, $8b, $51
	.byte $18, $f0, $8b, $8b, $29, $8b, $00, $89, $29, $83, $00, $83, $29, $91, $00, $83, $29, $83, $00, $83, $29, $95, $29, $8b
	.byte $00, $89, $29, $83, $00, $83, $27, $83, $00, $83
@song0ref1595:
	.byte $2d, $30, $34, $81, $2d, $30, $34, $00, $89, $2d, $30, $34, $2d, $30, $34, $2d, $30, $34, $2d, $30, $34, $39, $3c, $40
	.byte $4c, $81, $39, $3c, $40, $4c, $00, $89, $2d, $30, $34, $2d, $30, $34, $2d, $30, $34, $2d, $30, $34
	.byte $41, $2a
	.word @song0ref1595
@song0ref1642:
	.byte $29, $2d, $30, $81, $29, $2d, $30, $00, $89, $29, $2d, $30, $29, $2d, $30, $29, $2d, $30, $29, $2d, $30, $35, $39, $3c
	.byte $81, $35, $39, $3c, $00, $89, $29, $2d, $30, $29, $2d, $30, $29, $2d, $30, $29, $2d, $30
	.byte $41, $2a
	.word @song0ref1642
@song0ref1687:
	.byte $2b, $2f, $32, $81, $2b, $2f, $32, $00, $89, $2b, $2f, $32, $2b, $2f, $32, $2b, $2f, $32, $2b, $2f, $32, $37, $3b, $3e
	.byte $81, $37, $3b, $3e, $00, $89, $2b, $2f, $32, $2b, $2f, $32, $2b, $2f, $32, $2b, $2f, $32
	.byte $41, $2a
	.word @song0ref1687
	.byte $41, $2a
	.word @song0ref1642
@song0ref1735:
	.byte $28, $2c, $2f, $81, $28, $2c, $2f, $00, $89, $28, $2c, $2f, $28, $2c, $2f, $28, $2c, $2f, $28, $2c, $2f, $34, $38, $3b
	.byte $81, $34, $38, $3b, $00, $89, $28, $2c, $2f, $28, $2c, $2f, $28, $2c, $2f, $28, $2c, $2f
	.byte $41, $2a
	.word @song0ref1595
	.byte $41, $2a
	.word @song0ref1595
	.byte $41, $2a
	.word @song0ref1642
	.byte $41, $2a
	.word @song0ref1642
	.byte $41, $2a
	.word @song0ref1687
	.byte $41, $2a
	.word @song0ref1687
	.byte $41, $2a
	.word @song0ref1642
	.byte $41, $2a
	.word @song0ref1735
	.byte $41, $2a
	.word @song0ref1595
	.byte $41, $2a
	.word @song0ref1595
	.byte $41, $2a
	.word @song0ref1642
	.byte $41, $2a
	.word @song0ref1642
	.byte $41, $2a
	.word @song0ref1687
	.byte $41, $2a
	.word @song0ref1687
	.byte $41, $2a
	.word @song0ref1642
	.byte $41, $2a
	.word @song0ref1735
@song0ref1825:
	.byte $34, $8b, $32, $89, $34, $89, $2d, $89, $34, $8b, $32, $89, $34, $89, $2d, $89, $34, $8b, $32, $89, $34, $89, $2d, $89
	.byte $34, $8b, $32, $89, $34, $89, $2d, $89, $35, $8b, $34, $89, $35, $89, $30, $89, $35, $8b, $34, $89, $35, $89, $30, $89
	.byte $35, $8b, $34, $89, $35, $89, $30, $89, $35, $8b, $34, $89, $35, $89, $30, $89, $32, $8b, $30, $89, $2f, $89, $2b, $89
	.byte $32, $8b, $30, $89, $2f, $89, $2b, $89, $32, $8b, $30, $89, $2f, $89, $2b, $89, $32, $8b, $30, $89, $2f, $89, $2b, $89
	.byte $35, $8b, $34, $89, $30, $89, $2d, $89, $35, $8b, $34, $89, $30, $89, $2d, $89, $34, $8b, $2f, $89, $2c, $89, $32, $89
	.byte $34, $8b, $2f, $89, $2c, $89, $2f
	.byte $41, $1d
	.word @song0ref1383
	.byte $41, $23
	.word @song0ref1404
	.byte $41, $1d
	.word @song0ref1383
	.byte $41, $23
	.word @song0ref1404
	.byte $41, $1d
	.word @song0ref1383
	.byte $41, $23
	.word @song0ref1404
	.byte $41, $1d
	.word @song0ref1383
	.byte $35, $89, $32, $89, $00, $ff, $c5, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $b1, $86, $09
	.byte $8b, $00, $ff, $85, $80
	.byte $41, $40
	.word @song0ref1825
	.byte $41, $40
	.word @song0ref1825
	.byte $41, $40
	.word @song0ref1825
	.byte $41, $40
	.word @song0ref1825
	.byte $00, $ff, $c5, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7
	.byte $41, $2a
	.word @song0ref1595
	.byte $41, $2a
	.word @song0ref1595
	.byte $41, $2a
	.word @song0ref1642
	.byte $41, $2a
	.word @song0ref1642
	.byte $41, $2a
	.word @song0ref1687
	.byte $41, $2a
	.word @song0ref1687
	.byte $41, $2a
	.word @song0ref1642
	.byte $41, $2a
	.word @song0ref1735
	.byte $41, $2a
	.word @song0ref1595
	.byte $41, $2a
	.word @song0ref1595
	.byte $41, $2a
	.word @song0ref1642
	.byte $41, $2a
	.word @song0ref1642
	.byte $41, $2a
	.word @song0ref1687
	.byte $41, $2a
	.word @song0ref1687
	.byte $00, $ff, $c5, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $b1, $86, $09, $8b, $00, $ff, $85
	.byte $ff, $c7, $ff, $c7, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $74, $51, $01, $80, $88, $40, $59, $ff, $c5, $51, $02, $c0
	.byte $40, $59, $85, $40, $59, $d9, $51, $fd, $50, $e3, $51, $fc, $00, $40, $59, $af, $7f, $00, $ff, $93
	.byte $41, $1a
	.word @song0ref1322
	.byte $41, $1a
	.word @song0ref1322
	.byte $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7
	.byte $51, $f9, $00, $40, $59, $c9, $7f, $51, $f9, $00, $40, $59, $c7, $7f, $00, $af, $51, $f9, $00, $40, $59, $c9, $7f, $51
	.byte $f9, $00, $40, $59, $c7, $7f, $00, $af, $51, $f9, $00, $40, $59, $c9, $7f, $51, $f9, $00, $40, $59, $c7, $7f, $00, $af
	.byte $51, $fc, $00, $40, $5c, $ff, $93, $7f, $00, $af, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7
@song0ref2247:
	.byte $51, $fb, $00, $40, $59, $e1, $7f, $51, $fb, $00, $40, $59, $e1, $7f, $51, $fa, $70, $40, $59, $af, $7f, $51, $fa, $60
	.byte $40, $59, $af, $7f, $51, $f8, $90, $40, $59, $97, $7f, $51, $f8, $90, $40, $59, $95, $7f, $51, $f8, $90, $40, $59, $97
	.byte $7f, $51, $f6, $80, $40, $59, $95, $7f, $51, $fc, $00, $40, $5c, $ff, $93, $7f, $00, $af, $ff, $c7, $ff, $c7, $ff, $c7
	.byte $51, $fc, $00, $40, $5c, $ff, $93, $7f, $00, $af
	.byte $41, $1a
	.word @song0ref1322
	.byte $ff, $c7, $ff, $c7, $ff, $c7
@song0ref2338:
	.byte $ff, $c7, $ff, $c7, $70, $51, $03, $f0, $40, $58, $ff, $c5, $51, $fc, $00, $40, $5c, $ff, $93, $7f, $00, $af, $70, $51
	.byte $10, $a0, $40, $59, $91, $51, $fc, $00, $cf, $51, $10, $a0, $93, $51, $fc, $00, $cf, $51, $10, $a0, $40, $59, $91, $51
	.byte $fc, $00, $cf, $51, $10, $a0, $93, $51, $fc, $00, $cf, $51, $10, $a0, $40, $59, $91, $51, $fc, $00, $cf, $51, $10, $a0
	.byte $93, $51, $fc, $00, $cf, $51, $10, $a0, $40, $59, $91, $51, $fc, $00, $cf, $51, $10, $a0, $93, $51, $fc, $00, $cf, $51
	.byte $10, $a0, $40, $59, $91, $51, $fc, $00, $cf, $51, $10, $a0, $93, $51, $fc, $00, $cf, $51, $10, $a0, $40, $59, $91, $51
	.byte $fc, $00, $cf, $51, $10, $a0, $93, $51, $fc, $00, $cf, $51, $10, $a0, $40, $59, $91, $51, $fc, $00, $cf, $51, $10, $a0
	.byte $93, $51, $ff, $00, $cf, $00, $ff, $c5
	.byte $41, $1a
	.word @song0ref1322
	.byte $7f
	.byte $41, $20
	.word @song0ref2247
	.byte $41, $2e
	.word @song0ref2338
	.byte $51, $fc, $00, $cf, $51, $10, $a0, $40, $59, $91, $51, $fc, $00, $cf, $51, $10, $a0, $93, $51, $fe, $00, $cf, $00, $ff
	.byte $c5, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $c7, $04, $97, $00, $95, $04, $97, $00, $95, $04, $97, $00, $95, $04, $97, $00, $95, $ff, $c7, $ff, $c7, $ff, $c7
	.byte $ff, $95, $03, $8b, $03, $89, $03, $89, $03
@song0ref2562:
	.byte $89, $00, $97, $04, $89, $04, $89, $00, $97, $04, $89, $04, $89, $00, $97, $04, $89, $04, $89, $00, $97, $04, $89, $04
	.byte $89, $00, $97, $04, $89, $04
	.byte $41, $1e
	.word @song0ref2562
	.byte $89, $00, $97, $04, $89, $04, $89, $00, $97, $04, $89, $04, $89, $02, $97, $04, $83, $00, $83, $04, $83, $00, $83, $02
	.byte $97, $04, $83, $00, $83, $04, $83, $00, $83, $02, $97, $04, $83, $00, $83, $03, $89, $01, $97
@song0ref2638:
	.byte $03
@song0ref2639:
	.byte $89
@song0ref2640:
	.byte $03
@song0ref2641:
	.byte $89
@song0ref2642:
	.byte $02, $97, $04, $83, $00, $83, $03, $89, $01, $97, $03, $83, $00, $83, $03, $89, $02, $97, $04, $83, $00, $83, $03, $83
	.byte $03, $83, $01, $97, $04, $83, $00, $83, $04, $83, $00, $83
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
@song0ref2813:
	.byte $02, $97, $04, $89, $03, $89, $01, $97, $03, $89, $03, $89, $02, $97, $04, $89, $03, $89, $01, $8b, $03, $89, $03, $89
	.byte $04, $89, $02, $97, $04, $89, $03, $89, $01, $97, $03, $89, $03, $89, $01, $8b, $03, $89, $01, $89, $03, $89, $01, $8b
	.byte $02, $89, $01, $89, $01
	.byte $41, $1d
	.word @song0ref2641
	.byte $41, $20
	.word @song0ref2638
	.byte $03, $89, $04
	.byte $41, $1e
	.word @song0ref2641
	.byte $41, $1e
	.word @song0ref2639
	.byte $8b, $03, $89, $03, $89, $04
	.byte $41, $25
	.word @song0ref2641
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $01, $97, $01, $95, $01, $97, $01, $95, $01, $8b, $03, $89, $01, $89, $03, $89, $01, $8b, $00, $a1
	.byte $41, $1c
	.word @song0ref2642
	.byte $41, $1f
	.word @song0ref2638
	.byte $8b, $03, $89, $04
	.byte $41, $1f
	.word @song0ref2639
	.byte $41, $1f
	.word @song0ref2638
	.byte $8b, $03, $89, $04
	.byte $41, $1f
	.word @song0ref2639
	.byte $41, $1f
	.word @song0ref2638
	.byte $8b, $03, $89, $04
	.byte $41, $1f
	.word @song0ref2639
	.byte $41, $1b
	.word @song0ref2638
	.byte $89, $01, $97, $03, $83, $00, $83
	.byte $41, $26
	.word @song0ref2640
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $35
	.word @song0ref2813
	.byte $41, $25
	.word @song0ref2641
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $1d
	.word @song0ref2642
	.byte $41, $1e
	.word @song0ref2639
	.byte $8b, $03, $89, $03, $89, $04
	.byte $41, $25
	.word @song0ref2641
	.byte $41, $24
	.word @song0ref2642
	.byte $41, $24
	.word @song0ref2642
	.byte $01, $97, $01, $95, $01, $97, $01, $95, $01, $8b, $03, $89, $01, $89, $03, $89, $01, $8b, $00, $a1
	.byte $41, $1c
	.word @song0ref2642
	.byte $41, $1f
	.word @song0ref2638
	.byte $8b, $03, $89, $04
	.byte $41, $1f
	.word @song0ref2639
	.byte $41, $1f
	.word @song0ref2638
	.byte $8b, $03, $89, $04
	.byte $41, $1f
	.word @song0ref2639
	.byte $41, $1f
	.word @song0ref2638
	.byte $8b, $03, $89, $04
	.byte $41, $1f
	.word @song0ref2639
	.byte $41, $1b
	.word @song0ref2638
	.byte $89, $01, $97, $03, $83, $00, $83
	.byte $41, $1e
	.word @song0ref2640
	.byte $03, $89, $03, $89, $02, $af, $00, $ff, $93, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $7f, $80, $28, $8b, $24, $89, $21, $89, $1c, $89, $00, $ff
	.byte $93, $ff, $c7
@song0ref3185:
	.byte $ff, $c7, $cb, $24, $89, $23, $89, $20, $85, $21, $a7, $20, $97, $1c, $95, $00, $97, $82
@song0ref3203:
	.byte $1a, $95, $00, $97, $1a, $95, $00, $97, $1a, $95, $00, $97, $1a, $95, $00, $97, $15, $95, $00, $97, $15, $95, $00, $97
	.byte $13, $95, $00, $97, $13, $95, $00, $97, $1d, $95, $00, $97, $1d, $95, $00, $97, $1d, $95, $00, $97, $1d, $95, $00, $97
	.byte $1c, $89, $00, $89, $1c, $8b, $00, $89, $1c, $89, $00, $89, $1c, $8b, $00, $89, $1c, $89, $00, $89, $1c, $8b, $00, $89
	.byte $1c, $8f, $00, $83, $00, $97
	.byte $41, $38
	.word @song0ref3203
	.byte $80, $1c, $89, $1d, $89, $1c, $97, $1c, $89, $1d, $89, $1c, $8b, $1a, $89, $18, $89, $17, $89
@song0ref3303:
	.byte $20, $85, $21
@song0ref3306:
	.byte $ff, $8b, $51, $fc, $90, $b1, $7f, $1b, $85, $1c, $ff, $8b, $1c, $85, $1d, $a7, $19, $85, $1a, $ff, $bd, $17, $85, $18
	.byte $d9, $16, $85, $17, $d9, $14, $85, $15
	.byte $41, $1c
	.word @song0ref3306
	.byte $ff, $8b, $51, $fc, $90, $b1, $7f, $00, $ff, $c5
	.byte $41, $23
	.word @song0ref3185
	.byte $80, $28, $97, $82, $15, $95, $80, $28, $97, $82, $13, $89, $80, $26, $97, $00, $89, $24, $95, $00, $97, $82, $1d, $95
	.byte $00, $97, $1d, $95, $00, $97, $1d, $95, $00, $97, $1d, $95, $00, $97
@song0ref3392:
	.byte $1c, $89, $00, $89, $1c, $8b, $00, $89, $80, $1c, $89, $1d, $89, $1c, $97, $1c, $89, $1d, $89, $1c, $8b, $1a, $89, $18
	.byte $89, $17, $89, $00, $97, $82, $1a, $95, $00, $97, $1a, $95, $00, $97, $1a, $95, $00, $97, $1a, $95, $00, $97, $15, $95
	.byte $80, $28, $97, $82, $15, $95, $80, $28, $97, $82, $13, $89, $80, $26, $97, $00, $89, $24, $95, $24, $8b, $00, $89, $24
	.byte $89, $00, $89, $24, $8b, $00, $89, $23, $83, $24, $a9, $24, $89, $00, $89, $26, $97, $28, $95, $00, $97, $82
	.byte $41, $1c
	.word @song0ref3392
@song0ref3489:
	.byte $82
@song0ref3490:
	.byte $18, $95, $00, $97, $18, $95, $00, $97, $18, $95, $00, $97, $18, $95, $26, $8b, $00, $89, $28, $95, $00, $97, $24, $89
	.byte $00, $89, $26, $8b, $00, $89, $26, $89, $00, $89, $21, $97, $1f, $95, $21, $8b, $1f, $89, $49, .lobyte(@env13), .hibyte(@env13)
	.byte $21, $af, $51, $f8, $30, $49, .lobyte(@env0), .hibyte(@env0), $4a, $82, $50, $03, $2d, $2b, $af, $7f, $1a, $95, $00
	.byte $97, $1a, $95, $00, $97, $15, $95, $00, $97, $15, $95, $00, $97, $13, $95, $00, $97, $13, $95, $00, $97, $1a, $95, $00
	.byte $97, $1a, $95, $00, $97, $1a, $95, $00, $97, $1a, $95, $00, $af, $80, $28, $97, $00, $95, $28, $97, $00, $89, $26, $97
	.byte $00, $89, $2b, $95, $49, .lobyte(@env0), .hibyte(@env0), $4a, $26, $d5, $49, .lobyte(@env0), .hibyte(@env0), $4a, $50
	.byte $03, $32, $30, $a3, $00, $95, $24, $8b, $00, $a1, $00, $97, $82
	.byte $41, $2a
	.word @song0ref3392
	.byte $49, .lobyte(@env1), .hibyte(@env1), $80, $50, $f8, $32, $34, $8b, $80, $28, $bb, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $24, $83, $26, $a9, $1c, $89, $1d, $89, $1c, $8b, $1a, $89, $18, $89, $17, $89, $24, $97, $21, $a9, $22, $83, $49
	.byte .lobyte(@env4), .hibyte(@env4), $23, $af, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $1f, $95, $1d, $97, $1c, $95
	.byte $49, .lobyte(@env1), .hibyte(@env1), $50, $f8, $32, $34, $8b, $80, $28, $bb, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $24, $83, $26, $a9, $1c, $89, $1d, $89, $1c, $8b, $1a, $89, $18, $89, $17, $89
@song0ref3718:
	.byte $21, $8b, $51, $e8, $60, $8b, $51, $18, $f0, $8b, $8b, $21, $8b, $00, $89, $21, $83, $00, $83, $21, $91, $00, $83, $21
	.byte $83, $00, $83, $21, $95, $21, $8b, $00, $89, $21, $83, $00, $83, $1f, $83, $00, $83
	.byte $41, $23
	.word @song0ref3718
	.byte $41, $23
	.word @song0ref3718
	.byte $41, $23
	.word @song0ref3718
	.byte $41, $46
	.word @song0ref1513
	.byte $41, $3a
	.word @song0ref1513
	.byte $2b, $af
	.byte $41, $1f
	.word @song0ref3303
	.byte $41, $1c
	.word @song0ref3306
	.byte $41, $1c
	.word @song0ref3306
	.byte $ff, $8b, $51, $ff, $90, $b1, $00, $ff, $c5, $ff, $c7, $ff, $c7, $7f, $00, $97
	.byte $41, $46
	.word @song0ref3489
	.byte $41, $35
	.word @song0ref3490
	.byte $fb, $75, $84, $28, $83, $00, $83, $77, $28, $83, $00, $83, $79, $28, $85, $00, $83, $7b, $28, $83, $00, $83, $7d, $28
	.byte $83, $00, $83, $7f, $28, $83, $00, $83, $80
	.byte $41, $23
	.word @song0ref3718
	.byte $41, $23
	.word @song0ref3718
@song0ref3846:
	.byte $1f, $8b, $51, $e8, $60, $8b, $51, $18, $f0, $8b, $8b, $1f, $8b, $00, $89, $1f, $83, $00, $83, $1f, $91, $00, $83, $1f
	.byte $83, $00, $83, $1f, $95, $1f, $8b, $00, $89, $1f, $83, $00, $83, $1d, $83, $00, $83, $24, $8b, $51, $e8, $60, $8b, $51
	.byte $18, $f0, $8b, $8b, $24, $8b, $00, $89, $24, $83, $00, $83, $24, $91, $00, $83, $1c, $83, $00, $83, $1c, $95, $1c, $8b
	.byte $00, $89, $1c, $83, $00, $83, $1a, $83, $00, $83
	.byte $41, $23
	.word @song0ref3718
	.byte $41, $23
	.word @song0ref3718
	.byte $41, $23
	.word @song0ref3846
	.byte $41, $1a
	.word @song0ref3718
	.byte $a1, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7
	.byte $41, $1a
	.word @song0ref3718
	.byte $a1, $ff, $c7
	.byte $41, $1a
	.word @song0ref3846
	.byte $a1, $ff, $c7
	.byte $41, $1a
	.word @song0ref1513
	.byte $a1, $ff, $c7
	.byte $41, $3a
	.word @song0ref1513
	.byte $2b, $af
	.byte $41, $1f
	.word @song0ref3303
	.byte $ff, $8b, $51, $fc, $90, $b1, $7f, $1b, $85, $1c, $ff, $8b, $1c, $85, $1d, $a7, $19, $85, $1a, $ff, $bd, $00, $fb, $75
	.byte $84, $28, $83, $00, $83, $77, $28, $83, $00, $83, $79, $28, $85, $00, $83, $7b, $28, $83, $00, $83, $7d, $28, $83, $00
	.byte $83, $7f, $28, $83, $00, $83, $80
	.byte $41, $23
	.word @song0ref3718
	.byte $41, $23
	.word @song0ref3718
	.byte $41, $46
	.word @song0ref3846
	.byte $41, $23
	.word @song0ref3718
	.byte $41, $23
	.word @song0ref3718
	.byte $41, $23
	.word @song0ref3846
	.byte $41, $1a
	.word @song0ref3718
	.byte $a1
	.byte $41, $23
	.word @song0ref3718
	.byte $1c, $8b, $51, $f5, $90, $91, $51, $0b, $f0, $91, $99, $77, $8b, $72, $a5, $00, $c7, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $7f, $82
@song0ref4104:
	.byte $13, $85, $15, $a7, $50, $fb, $21, $23, $af, $17, $e1
@song0ref4115:
	.byte $00, $97, $1d, $95, $00, $97, $1d, $95, $00, $97, $1d, $95, $00, $97, $1d, $95, $00, $97, $1c, $95, $00, $97, $1c, $95
	.byte $00, $97, $1a, $95, $00, $97, $1a, $95, $00, $97, $15, $95, $00, $97, $15, $95, $00, $97, $15, $95, $00, $97, $15
@song0ref4162:
	.byte $95, $00, $97
@song0ref4165:
	.byte $1f, $89, $00, $89, $1f, $8b, $00, $89, $1f, $89, $00, $89, $1f, $8b, $00, $89, $23, $89, $00, $89, $23, $8b, $00, $89
	.byte $23, $89, $00, $89
	.byte $41, $4e
	.word @song0ref4115
	.byte $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7
	.byte $41, $56
	.word @song0ref4104
	.byte $00, $97, $1d, $95, $00, $97, $1d, $95, $00, $97, $1d, $95, $00, $97, $1d, $95, $00, $97, $1c, $95, $80, $24, $97, $82
	.byte $1c, $95, $80, $24, $97, $82, $1a, $89, $80, $23, $97, $00, $89, $1f, $95, $20, $85, $21, $c1, $50, $06, $2d, $2b, $95
	.byte $00, $e1, $00, $97, $82
	.byte $41, $1c
	.word @song0ref4165
@song0ref4277:
	.byte $00, $97
@song0ref4279:
	.byte $15, $95, $00, $97, $15, $95, $00, $97, $15, $95, $00, $97, $15, $95, $50, $fa, $2b, $2d, $97, $21, $ff, $ab, $21, $8b
	.byte $00, $89, $21, $89, $00, $89, $1f, $8b, $00, $89, $20, $83, $49, .lobyte(@env8), .hibyte(@env8), $21, $a9, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $82, $24, $89, $00, $89, $23, $97, $1f, $95, $00, $97, $1c, $95, $00, $97, $1c, $95, $00, $97
	.byte $1a, $95, $00, $97, $1a, $95
	.byte $41, $4e
	.word @song0ref4115
	.byte $00, $97, $1d, $95, $00, $97, $1d, $95, $00, $97, $1d, $95, $00, $97, $1d
	.byte $41, $1f
	.word @song0ref4162
	.byte $00, $97, $1d, $95, $00, $97, $1d, $95, $00, $97, $1d, $95, $00, $97, $1d
	.byte $41, $1f
	.word @song0ref4162
	.byte $80
@song0ref4389:
	.byte $1c, $8b, $51, $e8, $60, $8b, $51, $18, $f0, $8b, $8b, $1c, $8b, $00, $89, $1c, $83, $00, $83, $1c, $91, $00, $83, $1c
	.byte $83, $00, $83, $1c, $95, $1c, $8b, $00, $89, $1c, $83, $00, $83, $1a, $83, $00, $83, $1d, $8b, $51, $e8, $60, $8b, $51
	.byte $18, $f0, $8b, $8b, $1d, $8b, $00, $89, $1d, $83, $00, $83, $1d, $91, $00, $83, $1d, $83, $00, $83, $1d, $95, $1d, $8b
	.byte $00, $89, $1d, $83, $00, $83, $1b, $83, $00, $83
	.byte $41, $46
	.word @song0ref4389
	.byte $41, $23
	.word @song0ref3718
	.byte $41, $23
	.word @song0ref3718
	.byte $41, $23
	.word @song0ref3718
@song0ref4483:
	.byte $21, $8b, $51, $e8, $60, $8b, $51, $18, $f0, $8b, $8b, $21, $8b, $00, $89, $21, $83, $00, $83, $21, $91, $00, $83, $21
	.byte $83, $00, $83, $21, $95, $23, $af
@song0ref4514:
	.byte $49, .lobyte(@env2), .hibyte(@env2), $2d, $c9, $80, $26, $c7, $28, $af, $24, $e1, $51, $fc, $30, $e3, $7f, $26, $af
	.byte $24, $85, $26, $83, $24, $83, $26, $83, $2b, $c7, $21, $af, $24, $af, $26, $a7, $00, $27, $83, $28, $e1
	.byte $41, $20
	.word @song0ref4514
	.byte $49, .lobyte(@env2), .hibyte(@env2), $2d, $c9, $80, $26, $c7, $28, $af, $24, $e1, $51, $ff, $30, $e3, $00, $ff, $c5
	.byte $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $7f, $00, $97, $82
	.byte $41, $3b
	.word @song0ref4279
	.byte $41, $2d
	.word @song0ref4277
	.byte $80
@song0ref4597:
	.byte $1d, $8b, $51, $e8, $60, $8b, $51, $18, $f0, $8b, $8b, $1d, $8b, $00, $89, $1d, $83, $00, $83, $1d, $91, $00, $83, $1f
	.byte $83, $00, $83, $1f, $95, $1f, $8b, $00, $a1
	.byte $41, $46
	.word @song0ref4389
@song0ref4633:
	.byte $1a, $8b, $51, $e8, $60, $8b, $51, $18, $f0, $8b, $8b, $1a, $8b, $00, $89, $1a, $83, $00, $83, $1a, $91, $00, $83, $1a
	.byte $83, $00, $83, $1a, $95, $1a, $8b, $00, $89, $1a, $83, $00, $83, $18, $83, $00, $83, $1f, $8b, $51, $e8, $60, $8b, $51
	.byte $18, $f0, $8b, $8b, $1f, $8b, $00, $89, $1f, $83, $00, $83, $1f, $91, $00, $83, $17, $83, $00, $83, $17, $95, $17, $8b
	.byte $00, $89, $17, $83, $00, $83, $15, $83, $00, $83
	.byte $41, $46
	.word @song0ref4389
	.byte $41, $23
	.word @song0ref4633
	.byte $41, $1a
	.word @song0ref4389
	.byte $a1, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7, $ff, $c7
	.byte $41, $1a
	.word @song0ref4389
	.byte $a1, $ff, $c7
	.byte $41, $1a
	.word @song0ref4633
	.byte $a1, $ff, $c7
	.byte $41, $1a
	.word @song0ref3718
	.byte $a1, $ff, $c7
	.byte $41, $23
	.word @song0ref3718
	.byte $41, $39
	.word @song0ref4483
	.byte $49, .lobyte(@env2), .hibyte(@env2), $2d, $c9, $80, $26, $c7, $28, $af, $24, $e1, $51, $fe, $30, $e3, $00, $ff, $c5
	.byte $7f
	.byte $41, $1b
	.word @song0ref4597
	.byte $41, $46
	.word @song0ref4389
	.byte $41, $46
	.word @song0ref4633
	.byte $41, $46
	.word @song0ref4389
	.byte $41, $23
	.word @song0ref4633
	.byte $41, $1a
	.word @song0ref4389
	.byte $a1
	.byte $41, $23
	.word @song0ref4389
	.byte $21, $8b, $51, $f5, $90, $91, $51, $0b, $f0, $91, $99, $77, $8b, $72, $a5, $00, $c7, $42
	.word @song0ch6loop
